name: Convert Python scripts to Jupyter notebooks

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Jupytext
        run: |
          pip install 'jupytext~=1.0'

      - name: Convert Python scripts to notebooks
        run: |
          for script in scripts/*.py; do
            notebook=$(basename "$script" .py).ipynb
            jupytext --to ipynb "$script" --output notebooks/"$notebook"
          done

      - name: Create new branch, commit and push changes
        id: commit
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add notebooks/*.ipynb
          git diff --staged --quiet || echo "COMMIT=true" >> $GITHUB_ENV
          git commit -m "Add Jupyter notebooks" || echo "COMMIT=false" >> $GITHUB_ENV
          git push