name: Sync between Python scripts to Jupyter notebooks

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  sync_notebooks:
    runs-on: ubuntu-latest
    env:
      NOTEBOOK_FOLDER: notebooks
      SCRIPT_FOLDER: scripts
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Jupytext
        run: |
          pip install 'jupytext~=1.0'

      - name: Update notebook or script
        run: |
          shopt -s nullglob

          # Function to check which file was last modified
          function check_last_modified {
            file1=$1
            file2=$2

            # Get the hash of the last commit that modified each file
            last_commit_file1=$(git log -1 --format="%H" -- $file1)
            last_commit_file2=$(git log -1 --format="%H" -- $file2)

            # if one of the files does not exist, return the other
            if [ -z "$last_commit_file1" ]; then
              echo last
              return
            elif [ -z "$last_commit_file2" ]; then
              echo first
              return
            fi

            # compare commit hashes of files with last common commit hash
            last_common_commit=$(git merge-base $last_commit_file1 $last_commit_file2)
            if [ "$last_commit_file1" != "$last_common_commit" ]; then
              echo first
              return
            elif [ "$last_commit_file2" != "$last_common_commit" ]; then
              echo last
              return
            else
              echo both
              return
            fi
          }

          # locations of notebooks and scripts folders
          NOTEBOOK_FOLDER=${{ env.NOTEBOOK_FOLDER }}
          SCRIPT_FOLDER=${{ env.SCRIPT_FOLDER }}
          mkdir -p $NOTEBOOK_FOLDER $SCRIPT_FOLDER

          # catch all .py and .ipynb files, so the sync works if
          # (i) both files exist
          # (ii) either of the two exist
          for file in $NOTEBOOK_FOLDER/*.ipynb $SCRIPT_FOLDER/*.py; do

            # construct names for file pair
            base="${file##*/}"
            base="${base%.py}"
            base="${base%.ipynb}"
            notebook=$NOTEBOOK_FOLDER/"$base.ipynb"
            script=$SCRIPT_FOLDER/"$base.py"

            # Check which file was last modified
            last_modified=$(check_last_modified "$notebook" "$script")

            # update or create the paired file
            if [ "$last_modified" == "first" ]; then
              echo "Notebook file $notebook is older than script file $script. Updating notebook file."
              jupytext --update --to ipynb "$script" --output "$notebook"
              git add "$notebook"

            elif [ "$last_modified" == "last" ]; then
              echo "Notebook file $notebook is newer than script file $script. Updating script file."
              jupytext --opt notebook_metadata_filter="-all" --opt cell_metadata_filter="-all" --to py:percent "$notebook" --output "$script"
              git add "$script"

            elif [ "$last_modified" == "both" ]; then
              echo "Both $notebook and $script were last modified in same commit. Assuming they are in sync."
              
            fi
          done

      - name: Create new branch, commit and push changes
        id: commit
        run: |
          # shopt -s nullglob

          # Git setup
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # # add changes for notebooks and script files
          # NOTEBOOK_FOLDER=${{ env.NOTEBOOK_FOLDER }}
          # SCRIPT_FOLDER=${{ env.SCRIPT_FOLDER }}
          # git add $NOTEBOOK_FOLDER/*.ipynb $SCRIPT_FOLDER/*.py

          # commit and push changes
          git commit -m "Sync notebooks and script files" || echo "No changes to commit"
          git push
