name: Sync between Python scripts to Jupyter notebooks

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  sync_notebooks:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Jupytext
        run: |
          pip install 'jupytext~=1.0'

      - name: Convert Python scripts to notebooks
        run: |
          for file in notebooks/*.ipynb notebooks/scripts/*.py ; do
            jupytext --sync $file
          done

      - name: Create new branch, commit and push changes
        id: commit
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add notebooks/*.ipynb scripts/*.py
          git commit -m "Sync notebooks and script files" || echo "No changes to commit"
          git push